# input directory with inconsistent OG definitions
input_dir: test_data
# general output directory
output_dir: test_output
# final output directory for consistent OG definitions
consistent_ogs: test_output/consistent_ogs
# target taxonomic level to make consistent
target: 9443.tsv
# NCBI like taxonomy hierarchy (node -> parent)
level_hierarchy: data/eggNOG_tree.tsv

